config/routes.rb
Dueit::Application.routes.draw do
  resources :classes, :controller => :klasses, :only => %w(show index new create edit update)
  resources :members, :only => %w(new create destroy)

  resources :homework

  devise_for :accounts

  root :to => "home#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :homework, :foreign_key => :owner_id, :order => "state ASC, deadline ASC"

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def display_name
    email
  end
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :owner, :class_name => 'Account'

  validates :owner, :presence => true
  validates :name, :length => 3..140

  validates :deadline, :presence => true

  def how_soon
    soon = deadline - DateTime.current
    if soon < 0
      :overdue
    elsif soon < 1.day
      :tomorrow
    elsif soon < 2.days
      :two_days
    elsif soon < 1.week
      :week
    else
      :not_yet
    end
  end

  #
  # Any state other than "" or nil is considered done.
  def done?
    not state.blank?
  end
end

app/models/klass.rb
class Klass < ActiveRecord::Base
  has_many :members
  has_many :accounts, :through => :members
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :account
  belongs_to :klass
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if account_signed_in?
      @homework = current_account.homework
    end
  end

end

app/controllers/homework_controller.rb
class HomeworkController < ApplicationController
  private
  before_filter :authenticate_account!

  # For every action that needs to load a specific Homework, make this a before_filter
  before_filter :find_id, :only => %w(show edit update destroy)

  def find_id
    # Only access homework from your own account
    @homework = current_account.homework.find(params[:id])
    return true if @homework

    # Process the error
    flash.alert = "Homework #{params[:id]} not found"
    redirect_to root_url, :status => :not_found
    return false
  end

  public
  def show

  end

  def new
    @homework = Homework.new
  end

  def create
    @homework = Homework.new params[:homework].merge(:owner => current_account)
    if @homework.save
      # Success...
      flash.notice = "Homework '#{@homework.name}' created"
      redirect_to root_path
    else
      # Failure..
      flash.alert = "Failed: #{@homework.errors.full_messages.join(', ')}"
      render :action => "new"
    end
  end

  def edit
  end

  def update
    if @homework.update_attributes(params[:homework])
      # success
      flash.notice = "Homework '#{@homework.name}' updated"
       redirect_to root_path
    else
      # Failure
      flash.alert = "Failed: #{@homework.errors.full_messages.join(', ')}"
      render :action => "edit"
    end
  end

  def destroy
    @homework.destroy
    redirect_to root_url
  end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  private
  before_filter :authenticate_account!

  # For every action that needs to load a specific Homework, make this a before_filter
  before_filter :find_id, :only => %w(show edit update destroy)
  def find_id
    # Only access homework from your own account
    @klass = Klass.find(params[:id])
    return true if @klass

    # Process the error
    flash.alert = "Class #{params[:id]} not found"
    redirect_to root_url, :status => :not_found
    return false
  end

  public

  def show
  end

  def index
  end

  def new
    @klass = Klass.new
  end

  def create
    @klass = Klass.new(params[:class])
    if @klass.save
      flash.notice = "Class #{@klass.name} created."
      redirect_to class_url(@klass)
    else
      flash.alert = "Failed: #{@klass.errors.full_messages.join(', ')}"
      render :action => "new"
    end
  end

  def edit
  end

  def update
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homework_helper.rb
module HomeworkHelper
  def update_homework_state(homework, string, state)
    form_id = "state_#{state}_#{homework.id}"
    capture do
      form_for(homework, :html => {:id => form_id}) do |f|
        concat f.hidden_field(:state, :value => "done")
      end
    end + link_to_function(string, "$('##{form_id}').submit()")
  end
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/index.html.erb
<h1>DueIt Home</h1>

<% if account_signed_in? %>
<p>
  To begin, <%= link_to "Add New Homework", new_homework_path %> to
  remember some homework or <%= link_to "Create a Class", new_class_path %>.
</p>
<div id="homework_list">
  <ul>
    <%= render :partial => "homework/homework", :collection => @homework %>
  </ul>
</div>
<% else %>
<p>To use DueIt, you must <%= link_to "Sign In", new_account_session_path %>
  or <%= link_to "Register", new_account_registration_path %> an account.</p>
<% end %>

app/views/homework/_form.html.erb
<table> <tbody>
	<tr><th><%= form.label :name, 'Name' %></th>
  		<td><%= form.text_field :name %></td></tr>
  	<tr><th><%= form.label :criteria, 'Criteria' %></th>
  		<td><%= form.text_area :criteria %></td></tr>
  	<tr><th><%= form.label :deadline, 'Due Date' %></th>
 		<td><%= form.text_field :deadline %></td></tr>
 </tbody> </table> 

app/views/homework/_header.html.erb
<div class="homework-head <%= header.how_soon -%>">
<h3 class="left">
 <%= link_to_unless_current "#{header.deadline.to_date.to_formatted_s(:short)}: #{header.name}", homework_path(header), :title => "Click for details" %>

</h3>
<div class="ops right">
  <% if not header.done? %>
   <%= update_homework_state(header, "Done", "done") %>
  <% end %>
  <%= link_to "Edit", edit_homework_path(header) %>
 <%= link_to "Delete", homework_path(header), :method => :delete%>
</div>
<div class="clear"></div>
</div>

app/views/homework/_homework.html.erb
<% attrs = { :state => homework.state } %>
<% attrs[:soon] = homework.how_soon unless homework.done? %>
<%= content_tag_for :li, homework, attrs do %>
 <%= render :partial => "homework/header", :object => homework %>
<% end %>

app/views/homework/edit.html.erb
<%= form_for @homework do |f| %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update Homework" %>
<% end %>

app/views/homework/new.html.erb
<%= form_for @homework do |f| %>
  <%= f.label :name, 'Name' %>:
  <%= f.text_field :name %><br />
  <%= f.label :criteria, 'Criteria' %>:
  <%= f.text_field :criteria %><br />
  <%= f.label :deadline, 'Due Date' %>:
  <%= f.text_field :deadline %><br />
  <%= f.submit %>
<% end %>

app/views/homework/show.html.erb
<%= render :partial => "homework/header", :object => @homework %>

<p><%= @homework.criteria %> </p>

app/views/klasses/_form.html.erb
<table>
	<tbody>
	<tr>
	<td><%= form.label :name, "Class Name"%></td>
	<td><%= form.text_field :name %></td>
	</tr>
	<tr>
	<td><%= form.label :school %></td>
	<td><%= form.text_field :school %></td>
	</tr>
	<tr>
	<td><%= form.label :teacher %></td>
	<td><%= form.text_field :teacher %></td>
	</tr>
	<tr>
	<td><%= form.label :year %></td>
	<td><%= form.text_field :year %></td>
	</tr>
	<tr>
	<td><%= form.label :term %></td>
	<td><%= form.text_field :term %></td>
	</tr>
	<tr>
	<td><%= form.label :period %></td>
	<td><%= form.text_field :period %></td>
	</tr>
	</tbody>
</table>

app/views/klasses/create.html.erb
<h1>Klasses#create</h1>
<p>Find me in app/views/klasses/create.html.erb</p>

app/views/klasses/index.html.erb
<h1>Klasses#index</h1>
<p>Find me in app/views/klasses/index.html.erb</p>

app/views/klasses/new.html.erb
<%= form_for @klass, :as => :class, :url => classes_path do |f|%>
<%= render :partial => "form", :object => f %>
<%= f.submit "Create Class" %>
<% end %>

app/views/klasses/show.html.erb
<div class="class">
  <h1><%= @klass.name %></h1>
  <p>Find me in app/views/klasses/show.html.erb</p>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="left">
    Copyright Lee &amp; Maxwell Iverson, 2011
  </div>
  <div class="right">
    <%= link_to "About", "/about" %>
    <%= link_to "Privacy Policy", "/privacy" %>
  </div>
  <div class="clear"></div>
</div>

app/views/layouts/_header.html.erb
<div id="header" class="span-24 last">
  <div class="span-24 last">
    <div class="banner span-14">
      <span class="name">DueIt</span>
      Manage your homework
    </div>

    <div class="account span-10 last">
      <% if account_signed_in? %>
        <div class="left">
          Signed in as <%= current_account.display_name %>
        </div>
        <div class="right">
          <div><%= link_to("Sign Off", destroy_account_session_path, :method => 'delete') %></div>
        </div>
      <% else %>
        <div class="left">
         <em>Sign in or create an account.</em>
       </div>
       <div class="right">
          <div><%= link_to("Sign In", new_account_session_path)  %></div>
          <div><%= link_to("Register", new_account_registration_path)  %></div>
        </div>
     <% end %>
      <div class="clear"></div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dueit</title>
  <%= stylesheet_link_tag "screen.css", :media => "screen, projection" %>
  <%= stylesheet_link_tag "print.css", :media => "print" %>
  <!--[if lt IE 8]>
  <%= stylesheet_link_tag "ie.css", :media => "screen, projection" %>
  <![endif]-->

 <%= stylesheet_link_tag "cupertino/jquery-ui-1.8.14.custom.css" %>
 <%= stylesheet_link_tag "dueit.css" %>
 <%= csrf_meta_tag %>
</head>
<body>
  <div class="wrapper">
    <div class="container">
      <div class="span-24 last">
        <%= render :partial => "/layouts/header" %>
      </div>

      <div id="alerts" class="span-24 last">
        <% if notice %><div class="notice"><%= notice %></div> <% end %>
        <% if alert %> <div class="alert"><%= alert %></div> <% end %>
      </div>

      <div class="content span-24 last">
        <%= yield %>
      </div>
    </div>

    <div class="push"></div>
  </div>

  <%= render :partial => "/layouts/footer" %>

  <%= javascript_include_tag :defaults %>
</body>
</html>

app/views/members/create.html.erb
<h1>Members#create</h1>
<p>Find me in app/views/members/create.html.erb</p>

app/views/members/new.html.erb
<h1>Members#new</h1>
<p>Find me in app/views/members/new.html.erb</p>